extension.json
src/lib/dataElements/__tests__/constant.test.js
src/lib/dataElements/constant.js
src/view/dataElements/__tests__/constant.test.jsx
src/view/dataElements/constant.jsx

Add a "Constant" Data Element Type
The "Constant" Data Element Type allows users to make Data Elements that have a constant value.
When using Launch, there is often a need to keep things configurable, yet constant. A constant Data Element Type is highly useful for items like a report suite ID, or a tracking server.

Add Constant Data Element Type

---

yarn.lock

Cannot install yarn dependencies because a checksum fails for the collection-view dependency.
Updated the checksum.
Cannot install the dependencies otherwise.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ x ] All tests pass and I've made any necessary test changes.
- [ x ] I have run the extension sandbox successfully.

Update checksum for collection-view.

---

extension.json
src/lib/dataElements/__tests__/customCode.test.js
src/lib/dataElements/customCode.js

By adding support for event to be passed into the custom code data element type, users can create dynamic data elements that inspect the event context and take action conditionally. 
https://github.com/adobe/reactor-extension-core/issues/6
This update will allow the creation of data elements which act upon the additional payload passed as a second parameter of _satelllite.track.  It also opens up options to create data elements that return values appropriate to the context of evaluation (typically the trigger of the rule within which the data element is being evaluated). 
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ x ] …

added support for event to be passed into custom code data element type

---

src/view/conditions/cookie.jsx
src/view/conditions/hash.jsx
src/view/conditions/landingPage.jsx
src/view/conditions/path.jsx
src/view/conditions/pathAndQuerystring.jsx
src/view/conditions/queryStringParameter.jsx
src/view/conditions/subdomain.jsx
src/view/conditions/trafficSource.jsx
src/view/conditions/valueComparison.jsx
src/view/conditions/variable.jsx
src/view/configuration/configuration.jsx
src/view/dataElements/constant.jsx
src/view/dataElements/cookie.jsx
src/view/dataElements/domAttribute.jsx
src/view/dataElements/javascriptVariable.jsx
src/view/dataElements/localStorage.jsx
src/view/dataElements/queryStringParameter.jsx
src/view/dataElements/sessionStorage.jsx
src/view/events/components/elementPropertiesEditor.jsx
src/view/events/components/elementSelector.jsx
src/view/events/customEvent.jsx
src/view/events/dataElementChange.jsx
src/view/events/directCall.jsx
src/view/global.styl

in general the field lengths in the core extension views are short, this initial pr simply makes there longer by changing some css.
Perhaps there is a better way to make the field lengths more dynamic based on screen size, but i think it will require changes at the react-spectrum layer. 
Makes the extension more usable when long js or css paths are needed.

WIP - initial pass at increasing field lengths

---

src/lib/actions/helpers/decorators/__tests__/decorateHtmlCode.test.js
src/lib/actions/helpers/decorators/decorateHtmlCode.js

Forge replaces `onCustomCodeSuccess()` with `_satellite._onCustomCodeSuccess("${reactorCallbackId}")` (see the double quotes). The code and tests were expecting `_satellite._onCustomCodeSuccess(${reactorCallbackId})` (without the quotes).
The code could was functioning properly even with this inconsistency. That is because if you have `var x = {0: "some value"}`, when you call `x["0"]` you will get `"some value"` as a result (at least in Chrome.
Fixing an inconsistency.

Match the format emitted by Forge.

---

src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js

Stop using document.write and action sequencing is enabled.

Don't use document.write when action sequencing is enabled.

---

extension.json
src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js
src/lib/actions/helpers/__tests__/unescapeHtmlCode.test.js
src/lib/actions/helpers/unescapeHtmlCode.js

Postscribe doesn't handle HTML entity decoding for `style` and `script` tags. Taking care of that inside beforeWriteToken callback.
https://jira.corp.adobe.com/browse/DTM-15058

DTM-15058 Decode HTML entities from style and script tags.

---

src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js

When an external action didn't contain code an unhandled exception was thrown.
The error happens when an external custom code action has no content. This can happen in 2 cases:
When somebody adds an empty action to the build.
When somebody comments all the code from an action. The minifier will remove the comments, thus the emitted action will be empty.
https://jira.corp.adobe.com/browse/DTM-15195

DTM-15195 Handle the case when no code exists inside the action.

---

extension.json
src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js

Custom code action throws `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` for HTML code that contains comments.
https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=1676&selectedIssue=DTM-15203

DTM-15203 Handle tokens that don't have tagName property.

---

src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js
yarn.lock

OMEGA-1903: during customCode actions, pull the latest nonce from the extension settings on the fly.
In discussing a nonce timing issue, we noticed that when custom code actions run we use the nonce startup value. Since data elements can change over time, actions should use the latest value of nonce.
https://jira.corp.adobe.com/browse/OMEGA-1903

custom code actions - nonce on the fly

---

webpack.config.js

Due to the way Lens loads extension views in iframes, a JS error is thrown in the console.

Fix JS error that appears when the extension views are loaded in Lens.

---

src/view/configuration/__tests__/configuration.test.jsx
src/view/configuration/configuration.jsx

Users were unable to remove their previously saved CSP nonce value, because an empty string wasn't matching the save schema. Fixed this by removing the CSP nonce property from the settings block if the value is falsy.
https://jira.corp.adobe.com/browse/DTM-15636
Users can now remove their csp nonce values and save their changes in the extension configuration view.

Fixes bug where you couldn't remove CSP nonce value and save

---

.github/workflows/node.js.yml
extension.json
src/view/components/helpText.jsx
src/view/components/helpText.styl
src/view/components/warningContainer.jsx
src/view/conditions/__tests__/deviceType.test.jsx
src/view/conditions/sampling.jsx
src/view/conditions/valueComparison.jsx
src/view/events/__tests__/click.test.jsx
src/view/events/click.jsx
src/view/events/components/specificElements.jsx

Add a test for the deprecation message for deviceType.
As a part of the Link Delay epic, we've decided to sunset it as a recommended way to delay navigation. This adds a new warning message when the checkbox is turned on.
1. Show a deprecation message on link delay when it's turned on.
2. Introduces a Spectrum design pattern of "help text" below fields. https://spectrum.corp.adobe.com/page/help-text/#Icon
3. Converts other fields to use the new help text look, but maintains the old warning style for page level warnings
4. Tests when deprecation message shows up.
https://jira.corp.adobe.com/browse/DTM-16063

DTM-16063: show a deprecation message when Link Delay is on.

---

src/lib/conditions/__tests__/timeOnSite.test.js
src/lib/conditions/timeOnSite.js
src/lib/conditions/valueComparison.js
src/lib/events/__tests__/click.test.js
src/lib/events/__tests__/entersViewport.test.js
src/lib/events/__tests__/hover.test.js
src/lib/events/__tests__/mediaTimePlayed.test.js
src/lib/events/__tests__/timeOnPage.test.js
src/lib/events/click.js
src/lib/events/entersViewport.js
src/lib/events/hover.js
src/lib/events/mediaTimePlayed.js
src/lib/events/timeOnPage.js
src/lib/helpers/stringAndNumberUtils.js

DTM-13847: update runtime code to ensure new data element values are coerced to numbers when appropriate
There can be unforseen consequences of leaving the translated settings to values as strings when the data element values aren't coerced.
https://jira.corp.adobe.com/browse/DTM-13847

DTM-13847: coerce runtime strings to numbers

---

src/view/components/helpText.jsx
src/view/components/helpText.styl

When the `helpText` warning container was introduced, care was not taken to ensure that shrinking the viewable space didn't shrink the icon.
https://jira.corp.adobe.com/browse/PDCL-4859
Easy to notice in Lens since the viewable space is smaller than the entire screen.

PDCL-4859: fix warning icons getting crushed in views

---

src/lib/actions/__tests__/customCode.test.js
src/lib/actions/customCode.js
src/lib/actions/helpers/__tests__/getSourceByUrl.test.js
src/lib/actions/helpers/getSourceByUrl.js
src/lib/helpers/findPageScript.js

PDCL-6153: Core extension registers scripts based on the URL assigned by Turbine loading the script. This helps with Premium/Dynamic CDNs.
Changes that allow dynamic hosts
https://jira.corp.adobe.com/browse/PDCL-6153

Dynamic Host Updates

---

extension.json
src/view/dataElements/__tests__/conditionalValue.test.jsx
src/view/dataElements/conditionalValue.jsx

A few of the value comparison options had in JSON schema the conditional and fallback values as required. Also the schema didn't accept number values.
Also I updated the field label from this issue: https://github.com/adobe/reactor-extension-core/issues/64

Fix the JSON schema for some of the options.

---

src/lib/helpers/__tests__/getNamespacedStorage.test.js
src/lib/helpers/getNamespacedStorage.js

Customer stated that storage api's being disabled lead to failures, but it looks null safe to me. Added some logging.
https://jira.corp.adobe.com/browse/PDCL-6238

blackout-next(1) PDCL-6238: log warning when localStorage/sessionStorage unavailable

---

extension.json
karma.conf.js
package.json
src/lib/events/__tests__/keyDown.test.js
src/lib/events/__tests__/keyUp.test.js
src/lib/events/keyDown.js
src/lib/events/keyUp.js
src/view/events/keyDown.jsx
src/view/events/keyUp.jsx
yarn.lock

https://jira.corp.adobe.com/browse/PDCL-6233
Addresses #31 , which gives the user a way to hook into key events that aren't alphanumeric keys.

blackout-next(3) Pdcl 6233 support keyup keydown

---

.eslintignore
src/lib/events/__tests__/entersViewport.test.js
src/lib/events/entersViewport.js
src/lib/helpers/intersectionObserverIntervals.json
src/view/events/__tests__/change.test.jsx
yarn.lock

https://jira.corp.adobe.com/browse/PDCL-6794
* Addresses #60 to remove polling timing code from the entersViewport logic.
* Bumps some dependencies.

blackout-next(4) Pdcl 6794 modern approach enters viewport

---

extension.json
package.json
src/view/events/components/__tests__/specificElements.test.jsx

Fixes schema validation error for the `Form -> Change` event when `"and having certain property values..."` is active.
- the schema was nested 1 level too deep
The bug...
- If working in a new rule with the latest Core version, the UI will fail to validate
- After upgrading the Core extension new builds will fail due to old settings in rule components
The error...
`"The property 'elementProperties' of type array did not match the following type: object"`
See PDCL-11333 for more details.

PDCL-11333: Fix schema for `elementProperties` of Form-Change event

---

extension.json

Allows using of the **replaceAll** checkbox when using **Simple Replace** from the Data Element "Javascript Tools".
Closes #88 
https://jira.corp.adobe.com/browse/PDCL-13527
This option is already accounted for in the runtime code of the library, but the option does not pass the schema validation check in Forge.

Pdcl 13527 simple replace all
